version: '3.2'
services:
  postgresql:
    image: postgres:10.4
    volumes:
      - ./postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=database_books_user
      - POSTGRES_PASSWORD=ZpzFnKeW5mderMcHPGl8VfclRDMh43vX
    ports:
      - 5432:5432